### PR TITLE
Clarify non-standard values behavior for ResponseStatusCodeOnNoContext.

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by rhusar** [comment]
In response to the comment at https://issues.redhat.com/browse/JBCS-1642?focusedId=24208782&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24208782

**Review by jajik — APPROVED** [review]
LGTM, except "don't" would be better than "doesn't". And it will be the same way in the code (iirc, I copied it)...

**Comment by rhusar** [comment]
> LGTM, except "don't" would be better than "doesn't". And it will be the same way in the code (iirc, I copied it)...

In the code we have this:

        "ResponseStatusCodeOnNoContext - Response code returned when ProxyPass or ProxyMatch doesn't have matching context (Default: 404)"

**Comment by rhusar** [comment]
> LGTM, except "don't" would be better than "doesn't". And it will be the same way in the code (iirc, I copied it)...

Also, no: when you have a singular subject connected by "or," you should use a singular verb. In this case, "doesn't" is the contraction for "does not," which is the correct form.

**Comment by rhusar** [comment]
Also for the record,  the original PR for docs I opened was  https://github.com/modcluster/docs.modcluster.io/pull/172

**Comment by rhusar** [comment]
Thanks @jajik

**Pull request merged**
