### PR TITLE
Add a note about connectorPort behaviour with portOffset

### PR DESCRIPTION
**Pull request by jajik**
A note regarding https://github.com/modcluster/mod_cluster/pull/762

### CODE REVIEW

**Review by rhusar — APPROVED** [review]

**Comment by rhusar** [comment]
@jajik Should we add a note "Since 2.0.4.Final" ?

**Comment by jajik** [comment]
@rhusar Is it ok like this?

**Comment by rhusar** [comment]
> @rhusar Is it ok like this?

Definitely.

**Comment by rhusar** [comment]
Thanks @jajik

**Pull request merged**
