### PR TITLE
Fix misspelled EnableMCMPReceive option

### PR DESCRIPTION
**Pull request by jajik**
Once https://github.com/modcluster/mod_proxy_cluster/pull/202 gets merged.

### CODE REVIEW

**Comment by jajik** [comment]
Just fix for the misspelled misspell :smile:

**Comment by jajik** [comment]
(I was thinking about adding a note about the misspelled variant, but I don't think it's necessary.)

**Comment by rhusar** [comment]
> (I was thinking about adding a note about the misspelled variant, but I don't think it's necessary.)

I am afraid we have to include it.... e.g. for CTRK+F use cases...

**Review by rhusar — CHANGES_REQUESTED** [review]
Please add a note about the deprecated version with information since which release this is fixed. Perhaps in a NOTE: block

**Review by rhusar — APPROVED** [review]
LGTM now

**Comment by jajik** [comment]
@rhusar  Note added. I also spotted a typo, so I dared to add a fix here instead of opening a new PR...

**Comment by rhusar** [comment]
> @rhusar Note added. I also spotted a typo, so I dared to add a fix here instead of opening a new PR...

haha, that's totally fine :) thx

**Comment by jajik** [comment]
Well, that was fast. :D Thanks for the merge.

**Pull request merged**
