### PR TITLE
ci: Use built docs in Deploy job, use single file

### PR DESCRIPTION
**Pull request by jajik**
The deployment can use the `ci` artifact directly instead of building again (it needs to be in the same file, but that seems like an acceptable change).

### CODE REVIEW

**Comment by rhusar** [comment]
Good idea, the price we pay is this ugliness on every PR:

image

**Comment by jajik** [comment]
That's fine by me :man_shrugging: (I'm more concerned with the ugly `if` in the `.yaml` file :smile: but I won't look at it unless something breaks or so...)

**Comment by rhusar** [comment]
Ironically, I have been trying to move away from having a single workflow for PR and upstream/main since they have different scopes (deploy, publish snapshot, publis javadoc, etc).

This will also break the icon in README and the link (https://github.com/modcluster/docs.modcluster.io/actions/workflows/deploy.yml) but I will fix that.

**Review by rhusar — APPROVED** [review]
Let's try this!

**Comment by rhusar** [comment]
@jajik Are you sure this works? because it doesn't - https://github.com/modcluster/docs.modcluster.io/actions/runs/11328040976

**Comment by jajik** [comment]
Well, I wanted to preserve the `deploy.yml` file, but it is required to have one action without dependencies in each file...

**Comment by rhusar** [comment]
I think you misunderstood what 'needs' actually does in GHA..

**Comment by jajik** [comment]
Nope, the checkout is missing because I did not realize the gh-pages stuff needs that.

**Comment by jajik** [comment]
I'll fix it after a meeting

**Comment by rhusar** [comment]
> Nope, the checkout is missing because I did not realize the gh-pages stuff needs that.

Right - the 'deploy' job just doesn't have the checkout nor nothing else from the 'ci' job for that matter..

**Pull request merged**
