### PR TITLE
Add a short description on insert/update for *-APP cmds

### PR DESCRIPTION
**Pull request by jajik**

### CODE REVIEW

**Review by rhusar — APPROVED** [review]

**Comment by rhusar** [comment]
Just a quick hotfix: https://github.com/modcluster/docs.modcluster.io/commit/cd58c7fd53e6007d61b265c9f10010f4bcfa8173

**Comment by rhusar** [comment]
Thanks @jajik

**Comment by jajik** [comment]
> Added just a quick hotfix: [cd58c7f](https://github.com/modcluster/docs.modcluster.io/commit/cd58c7fd53e6007d61b265c9f10010f4bcfa8173)

Thanks, double check is not enough today... :roll_eyes:

**Comment by rhusar** [comment]
> > Added just a quick hotfix: [cd58c7f](https://github.com/modcluster/docs.modcluster.io/commit/cd58c7fd53e6007d61b265c9f10010f4bcfa8173)
> 
> Thanks, double check is not enough today... 🙄

Sometimes not even triple check is enough (when there is scarcity of morning coffees) :-D

**Pull request merged**
